module.exports = (sequelize, Sequelize) => {
  const Measurements = sequelize.define("measurements", {
      lat: {
        type: Sequelize.FLOAT
      },
      lon: {
        type: Sequelize.FLOAT
      },
      level: Sequelize.INTEGER,
      speed: Sequelize.INTEGER,
      operatorname: Sequelize.STRING,
      mcc: Sequelize.STRING,
      mnc: Sequelize.STRING,
      node:Sequelize.INTEGER,
      cellid: Sequelize.INTEGER,
      network_type: Sequelize.INTEGER,
      qual: Sequelize.INTEGER,
      snr: sequelize.INTEGER,
      cqi: Sequelize.INTEGER,
      lterssi: Sequelize.INTEGER,
      psc: Sequelize.INTEGER,
      arfcn: Sequelize.INTEGER,
      ta: Sequelize.INTEGER,
      ip: Sequelize.STRING,
      dl_bitrate: Sequelize.INTEGER,
      ul_bitrate: Sequelize.INTEGER,
      nlac1: Sequelize.INTEGER,
      ncellid1: Sequelize.INTEGER,
      nrxlev1: Sequelize.INTEGER,
      nqual1: Sequelize.INTEGER,
      narfcn1: Sequelize.INTEGER,
      nlac2: Sequelize.INTEGER,
      ncellid2: Sequelize.INTEGER,
      nrxlev2: Sequelize.INTEGER,
      nqual2: Sequelize.INTEGER,
      narfcn2: Sequelize.INTEGER,
      nlac3: Sequelize.INTEGER,
      ncellid3: Sequelize.INTEGER,
      nrxlev3: Sequelize.INTEGER,
      nqual3: Sequelize.INTEGER,
      narfcn3: Sequelize.INTEGER,
      nlac4: Sequelize.INTEGER,
      ncellid4: Sequelize.INTEGER,
      nrxlev4: Sequelize.INTEGER,
      nqual4: Sequelize.INTEGER,
      narfcn4: Sequelize.INTEGER,
      nlac5: Sequelize.INTEGER,
      ncellid5: Sequelize.INTEGER,
      nrxlev5: Sequelize.INTEGER,
      nqual5: Sequelize.INTEGER,
      narfcn5: Sequelize.INTEGER,
      nlac6: Sequelize.INTEGER,
      ncellid6: Sequelize.INTEGER,
      nrxlev6: Sequelize.INTEGER,
      nqual6: Sequelize.INTEGER,
      narfcn6: Sequelize.INTEGER,
      event: Sequelize.STRING,
      eventdetails: Sequelize.STRING,
      accuracy: Sequelize.INTEGER,
      locationsource: Sequelize.STRING,
      altitude: Sequelize.INTEGER,
      conntype: Sequelize.STRING,
      conninfo: Sequelize.STRING,
      avgping: Sequelize.INTEGER,
      minping: Sequelize.INTEGER,
      maxping: Sequelize.INTEGER,
      stdevping: Sequelize.INTEGER,
      pingloss: Sequelize.INTEGER,
      testdlbitrate: Sequelize.INTEGER,
      testulbitrate: Sequelize.INTEGER,
      testulmaxbitrate: Sequelize.INTEGER,
      network_typenum: Sequelize.INTEGER,
      msisdn: Sequelize.STRING,
      imsi: Sequelize.STRING,
      imei: Sequelize.STRING,
      phone_type: Sequelize.STRING,
      band: Sequelize.STRING,
      bandwidth: Sequelize.INTEGER,
      comment: Sequelize.STRING,
      battery: Sequelize.INTEGER,
      charging: Sequelize.STRING,
      username: Sequelize.STRING,
      password: Sequelize.STRING,
      teststate: Sequelize.STRING,
      buffer: Sequelize.INTEGER,
      credits: Sequelize.INTEGER,
      ctime: {
        type: Sequelize.DATE,
      },
      imported: Sequelize.INTEGER,
      versionname: Sequelize.STRING,
    },
    {
      timestamps: false
    });
  return Measurements;
};
